package it.unibo.myvet.utils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Database implements AutoCloseable {
    private Connection connection;

    // Costruttore privato per forzare l'uso del factory method
    private Database(Connection connection) {
        this.connection = connection;
    }

    // Metodo statico per creare un'istanza di Database
    public static Database connect(String url, String user, String password) throws SQLException {
        Connection connection = DriverManager.getConnection(url, user, password);
        return new Database(connection);
    }

    // Metodo per preparare un PreparedStatement
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    // Metodo per preparare un PreparedStatement che supporta RETURN_GENERATED_KEYS
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    // Metodo per chiudere la connessione al Database
    @Override
    public void close() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }
}
